### ISSUE TITLE
error 'playsound' library

### ISSUE THREAD

**Issue by nouriadnen** [TaylorSMarks/playsound#11]
![error](https://user-images.githubusercontent.com/29691674/33162039-0dd32178-d030-11e7-9ce6-26ad94e0137c.PNG)

who can help me to solve this problem?

**Comment by TaylorSMarks** [comment]
The Linux portion of the code really isn’t mine anymore. It looks like the issue is there’s something called gi being imported and that module’s __init__.py file has a Python 2 style call to print.

I’d suggest using Python 2 instead. If that’s not an option, go modify that file (the stack trace says exactly where it is) and put parentheses around the argument (url) being given to print, exactly like the error message says to do.

This is a free open source project. Why do people think they’re entitled to any support? Makes me feel like sharing less code in the future.
