### ISSUE TITLE
Program freezes after song finishes playing (blocking=true, window 7, temp solution included)

### ISSUE THREAD

**Issue by yobleck** [TaylorSMarks/playsound#47]
I'm mostly using this for Linux but when I ported my code over to windows I discovered that the program would just sit there after playing a song. I figured out that on line 37 
`durationInMS = winCommand('status', alias, 'length')`
returns twice the length of the song in Milliseconds.
i.e. if the song is 1 minute long it will return 2 minutes worth of MS.
The short term solution is to replace 1000 with 2000 on line 41.
IDK if this is an issue with playsound or windll.winmm and if the bug is window 7 only or affects later versions as well. I'm just putting this here in case anyone else has the same issue and needs a quick fix

**Comment by yobleck** [comment]
I haven't tested this but changing
`winCommand('play', alias, 'from 0 to', durationInMS.decode())`
to
`winCommand('play', alias, 'from 0 to', int(durationInMS.decode()/2))`

might work as well assuming the file is actually playing for twice as long as its suppose to.

**Comment by TaylorSMarks** [comment]
Please make a PR adding in your file which doesn't work in test_media and using it in test.py.

**Comment by yobleck** [comment]
It was all audio files, not just one. But if you don't mind my saying so, I don't think it matters anymore, since I don't have windows installed anymore and no one has reported the issue with Win10 so I'm assuming it was a Win7 issue (or just a me specifically issue)

**Comment by TaylorSMarks** [comment]
When I last had a computer running Windows 7 (~5 years ago now), playsound was running fine on it.

playsound has always run fine on my WIndows 10 computer. Travis-CI isn't reporting any issues running on Windows, but it's using Windows Server 2016, and it doesn't have proper audio drivers so I have to mock/patch the tests running there so I'm not sure how useful those tests are anyways....

Anyways... I'm going to leave this issue closed now since it doesn't matter to your personally, nobody else has mentioned it, and neither of us have any ideas for how to reproduce it.
