### ISSUE TITLE
ModuleNotFoundError: No module named 'AppKit'

### ISSUE THREAD

**Issue by RafaelCenzano** [TaylorSMarks/playsound#51]
Error running on macOS Catalina (10.15.6) with python 3.8.5. ModuleNotFoundError: No module named 'AppKit'

**Comment by radroid** [comment]
I have the same problem.

**Comment by jamrod** [comment]
I had to install PyObjC to fix this issue.
Try this
pip3 install -U PyObjC

**Comment by ahmeterhan2727** [comment]
I tried that, but my issue wasn't solved

**Comment by ShinyWobbuffet** [comment]
> I had to install PyObjC to fix this issue.
> Try this
> pip3 install -U PyObjC

It worked! But doesn't the project say it has no dependencies?

**Comment by TaylorSMarks** [comment]
What is the module that comes with the system copy of Python on macOS?

playsound isn't supposed to have any dependencies - I'm thinking about the possibility of making it so that playsound modifies the path when running on macOS so that it has access to that built-in module...

I think that'll be the best possible solution... I'll try figuring it out during the long holiday weekend...

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have not added PyObjC as a hard dependency, but I print out a suggestion that you aught to install it. Even without it, the code still works on Python 3 on Mac, by shelling out to Mac OS's built-in python.
